# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               AFIT Data Science Lab R Programming Guide
tagline:             ''
description:         '<img src="https://media.defense.gov/2015/Jun/03/2001051879/-1/-1/0/150603-F-PB123-104.JPG" height=100 </img>'
url:                 https://afit-r.github.io
baseurl:             ''

