# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               <img src="https://raw.githubusercontent.com/afit-r/afit-r.github.io/master/public/DSL_logo.png" height=100 </img> AFIT Data Science Lab R Programming Guide
tagline:             ''
description:         '<img src="https://raw.githubusercontent.com/afit-r/afit-r.github.io/master/public/DSL_logo.png" height=150 </img>'
url:                 https://afit-r.github.io
baseurl:             ''

