# Site settings
title: R Programming @ UC
email: bradleyboehmke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "http://r-uc.github.io/" # the subpath of your site, e.g. /blog/
url: "http://r-uc.github.io/" # the base hostname & protocol for your site
twitter_username: bradleyboehmke
github_username:  uc-r
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
